### ISSUE TITLE
Navigation maybe should be based on viewtype not viewmodeltype

### ISSUE THREAD

**Issue by Arthur-Lee** [bezysoftware/MVVM-Navigation#4]
this is awesome framework to implement the MVVM model, however I think navigation based on viewtype maybe better not based on viewmodeltype ( service.Navigate(viewModelType) in NavigationToview file). 
            for example, i have one mainpage , i want my mainpage have different view layout according to the Windows size. the optical choice is to implement different page on different size,they will be corresponding to the same MainPageViewModel, the navigation can't happened in your navigation way.

**Comment by bezysoftware** [comment]
Actually, this is something that an interceptor should do. The VM shouldn't know anything about the View - it should always navigate only to another VM. 
During the navigation processing, the PlatformNavigator delegates the navigation request to the interceptors and they are able change the target / prevent the plaftorm navigation completely. 
You can take u look at the MVVM-Dialogs (https://github.com/bezysoftware/MVVM-Dialogs) which uses this - for example following:

navigationService.Navigate<DialogViewModel>()

can show a dialog on a big screen, but it takes you to a new page on a small screen.

**Comment by Arthur-Lee** [comment]
thank for your reply. Attribute AssociatedDialogViewModel indicate which "popup" will show when the InnerNavigationInterceptor(viewType) is true. when the "popup" show, the beneath viewType still be there decide when it will show again. this is very cool~
But there is a idea coming to me when I study your sample.  A view may have different page on different condition. there should be a "Group" attribute to manage all the page have the specific "Group" attribute, all the different page can share the same ViewModel. when Navigation happens , just navigate to a "Group" , the "Group" will know which page will show on this condition. this will make all the layout stuff more easy.
BTW, this is my simple thought, maybe it's more difficult to implement than your method.

**Comment by wavebit** [comment]
Hello, 
I agree with Arthur-Lee. If you navigate a view model A to another view model B, you may expose many unneeded interfaces of B to A. And one view model can be shared by multiple views, if you navigate to one of the views with view model, which one is the targe?
